name: masticat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.4
  flutter_local_notifications: ^9.4.0
  image_picker: ^0.8.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/Logo.png
    - lib/images/catcam.gif
    - lib/images/cardluna.jpeg
