name: masticat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  retrofit: ^4.4.0
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  fl_chart: ^0.40.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/catcam.gif
    - lib/images/cardluna.jpeg
    - lib/images/Logo.png
